/** Review session design tokens — pixel-match to Flipwise review HTML mock. */
export const reviewTokens = {
  background: '#FFFFFF',
  surface: '#F8F9FD',
  surfaceVariant: '#E1E2E6',
  surfaceContainer: '#ECEEF2',
  surfaceContainerLow: '#F2F3F7',
  card: '#FFFFFF',
  cardStack: '#F7F8F5',
  border: '#E5E7EB',
  primary: '#516600',
  primaryContainer: '#C6F135',
  primaryFixedDim: '#ACD60E',
  secondary: '#5C5F5D',
  onSurface: '#191C1F',
  muted: '#6B7280',
  ink: '#1A1A1A',
  againBg: '#FEF2F2',
  againText: '#EF4444',
  hardBg: '#FFFBEB',
  hardText: '#D97706',
  goodBg: '#F7FEE7',
  goodText: '#516600',
  easyBg: '#C6F135',
  easyText: '#1A1A1A',
  cardRadius: 20,
  stackOffset: 4,
} as const;
