/** Design tokens for APIs that cannot use Tailwind classes (ActivityIndicator, navigation, SVG). */
export const colors = {
  background: '#F5F6F3',
  reviewBg: '#FFFFFF',
  libraryBg: '#F5F6F3',
  ink: '#1A1A1A',
  mutedSubtitle: '#8A8D85',
  surface: '#FFFFFF',
  surfaceBright: '#F8F9FD',
  surfaceMuted: '#F2F3F7',
  card: '#FFFFFF',
  primary: '#516600',
  primaryContainer: '#C6F135',
  onPrimaryContainer: '#556B00',
  accent: '#C6F135',
  accentMuted: '#EEF8D4',
  text: '#191C1F',
  onSurface: '#191C1F',
  muted: '#6B7280',
  onSurfaceVariant: '#444934',
  placeholder: '#6B7280',
  border: '#E5E7EB',
  outlineVariant: '#C5C9AE',
  surfaceVariant: '#E1E2E6',
  surfaceContainer: '#ECEEF2',
  secondary: '#5C5F5D',
  danger: '#EF4444',
  dangerMuted: '#FEF2F2',
  warningMuted: '#FFFBEB',
  warningText: '#D97706',
  goodMuted: '#F7FEE7',
  primaryFixedDim: '#ACD60E',
  errorContainer: '#FFDAD6',
  secondaryContainer: '#DFE0DD',
  onSecondaryContainer: '#616361',
  tertiary: '#476178',
  tertiaryContainer: '#C9E4FF',
  warning: '#F59E0B',
  warningBar: '#FBBF24',
  fabGreen: '#C6F135',
  fabDark: '#1A1A1A',
  success: '#2F855A',
  white: '#FFFFFF',
  black: '#191C1F',
  silhouette: '#F7F8F5',
  brandLavender: '#E8DEFF',
  brandPink: '#FFE4F0',
  brandMint: '#D4F5E9',
  brandSky: '#D6EEFF',
  brandYellow: '#FFF3CD',
  shadow: 'rgba(0, 0, 0, 0.04)',
  shadowMedium: 'rgba(0, 0, 0, 0.08)',
} as const;

export const fonts = {
  display: 'Manrope-Bold',
  displayMedium: 'Manrope-SemiBold',
  body: 'Inter-Regular',
  bodyMedium: 'Inter-Medium',
  bodySemiBold: 'Inter-SemiBold',
} as const;

export const radii = {
  card: 20,
  button: 12,
  input: 12,
  huge: 20,
  pill: 9999,
} as const;

export const navigationTheme = {
  headerStyle: {backgroundColor: colors.background},
  headerTintColor: colors.text,
  headerTitleStyle: {
    fontFamily: fonts.bodySemiBold,
    fontWeight: '600' as const,
    color: colors.text,
    fontSize: 17,
  },
  headerShadowVisible: false,
  contentStyle: {backgroundColor: colors.background},
};
